16-Absolute-Positivity.size.speed.asm
Got a solution for level 16 that satisfies both speed and size.
=> Added a solution for 16 that is both speed and size

28-Three-Sort.speed.asm
Here's a speed solution for three sort.  It's messy but necessarily so I believe.  There's also some comments to make the code a little more readable because it is not intuitive.
=> Add Three Sort speed solution

20-Multiplication-Workshop.speed.asm
Uses a tail-merged multiply table
=> 84 step solution

31-String-Reverse.size.asm
So this is one under par in size but ends up being one over par for speed.
=> A smaller sized solution for #31

02-Busy-Mail-Room.speed.asm
=> 20 step solution to 02-Busy Mail Room

39-Re-Coordinator.speed.asm, 40-Prime-Factory.speed.asm
39-Re-Coordinator.speed.asm
51 step solution achieved by unrolling the loop.
=> Add 51 step solution for Year 39

39-Re-Coordinator.size.asm, 39-Re-Coordinator.speed.asm
Exact solution for 39 Re-Coordinator, with 14/14 and 76/76. Named as
.size only since my previous .speed solution is faster. Rename if you
prefer.
=> Exact solution for 39 Re-Coordinator

22-Fibonacci-Visitor.speed.asm
Build the Fibonacii sequence once, then scan it repeatedly, with an unrolled scan loop for speed.
=> 74-cycle 50-instruction solution

24-Mod-Module.size.speed.asm
My first contribution. I hope I'm doing this right.
=> Add 24-Mod-Module.size.speed.asm

12-Tetracontiplier.size.speed.asm
Disregard if more recent alternatives will not be taken. Thought this is simpler though.
=> Same stats but uses less memory

40-Prime-Factory.speed.asm, README.md
Adds 277 cycle solution for floor 40: Prime Factory.
=> 277 cycle solution for 40-Prime-Factory.speed.asm

13-Equalization-Room.speed.asm
=> 13-Equalization-Room.speed.asm - 25 Steps Solution

20-Multiplication-Workshop.speed.asm
Always start multiplying from one of factors, instead of zero.
=> 81 cycle solution to 20-Multiplication-Workshop.speed.asm

16-Absolute-Positivity.speed.asm
=> 16-Absolute-Positivity.speed.asm - 30 Steps Solution

40-Prime-Factory.size.asm
Improved my own solution by two commands.
=> A 23-command solution to 40 Prime Factory

19-Countdown.speed.asm
=> 19-Countdown.speed.asm - 65 Steps Solution

25-Cumulative-Countdown.speed.asm
=> 25. More speed

16-Absolute-Positivity.speed.asm, 17-Exclusive-Lounge.size.speed.asm
=> 17-Exclusive-Lounge.size.speed.asm

38-Digit-Exploder.speed.asm
=> 38-Digit-Exploder.speed.asm - 133 Steps Solution

22-Fibonacci-Visitor/speed-Patrick-Jakubowski.asm
Some serious tweaks, now doesn't write the inbox'd number to memory, saves a lot of cycles with that, and saves more by not looping and terminating in 2 numbers, which is always true in this challenge.
=> 52 Cycle Fibonacci

17-Exclusive-Lounge/12-27 - AaronKnowles.asm
=> Create 12-27 - AaronKnowles.asm

17-Exclusive-Lounge/speed-og01.asm, README.md
=> 25/28 speed record for 17 - Exclusive Lounge

21-Zero-Terminated-Sum/28.58.exploit-AaronKnowles.asm, 21-Zero-Terminated-Sum/29.60-AaronKnowles.asm
Exploit version is -7 SIZE & -3 SPEED versus current speed program.
Non-exploit version is -6 SIZE & -1 SPEED versus current speed program.
=> 21 zero terminated sum

39-Re-Coordinator/speed-Otto42.asm
=> Reduce speed by moving inbox calls around

02-Busy-Mail-Room-3.25/24.20.specific-peterfreese.asm
Corrected program size from 26 to 24
=> Update and rename 26.20.specific-peterfreese.asm to 24.20.specific-peterfreese.asm

20-Multiplication-Workshop-15.109/157.72-mschordan.asm
Hi, this is a solution with speed 72 for Level 20 Multiplication-Workshop. It appears to be faster by 1 than the current record with 73.
=> Level 20 - Multiplication-Workshop with speed 72.

30-String-Storage-Floor-7.203/79.101-Otto42.asm
Cheaty solution, the program knows the message in advance. Avoids using loops except when necessary.
=> Level 30 - Speed 101 solution

30-String-Storage-Floor-7.203/8.177.asm, README.md
=> 30-String-Storage-Floor - SIZE 8/7 - SPEED 177/203

41-Sorting-Floor-34.714/mergesort-IAmWave.asm
It is really big and really show, but it is merge sort. In a way.
=> A merge sort solution to 41

22-Fibonacci-Visitor-19.156/17.148-tuxuin.asm
Former Record 18.154, now 17.148
=> New solution for size challenge of 22 - Fibonacci Visitor (17/19)

19-Countdown-10.82/10.111-jlmitch5.asm
This is very close to the hermanprawiro's solution, the difference being that I reduced the amount of times the "check if zero" loop is hit, by nesting under "check if negative's" false-y state.
=> solution 10, size par, a little closer to speed par

31-String-Reverse-11.122/11.118-johanatan.asm
11/118 solution for String Reverse.
=> 11/118 solution for String Reverse.

20-Multiplication-Workshop-15.109/161.70.specific-mschordan.asm
This improves on the existing solution(s) to a speed of 70.
=> level20: added speed 70 solution.

20-Multiplication-Workshop-15.109/93.67.specific-schordan.asm
Adapted  solution to bump speed down to 67.
=> Added level 20 - speed 67.

20-Multiplication-Workshop-15.109/92.64.specific-schordan.asm, 20-Multiplication-Workshop-15.109/93.65.specific-schordan.asm
Reordered some of the jumps to make structure clearer. Eliminated one jump giving speed 64.
=> Level20 improvements - speed 64

41-Sorting-Floor-34.714/112.481.specific-viamodulo.asm
Hi! I couldn't find the top scores file to update, so you'll have to do that while merging. :)
=> Speed 481 for level 41

contributors.yml, solutions/19-Countdown-10.82/116.57.specific-Eirik0.asm, solutions/20-Multiplication-Workshop-15.109/185.49.specific-Eirik0.asm, solutions/23-The-Littlest-Number-13.75/58.29.specific-Eirik0.asm, solutions/28-Three-Sort-34.78/29.117-Eirik0.asm, solutions/41-Sorting-Floor-34.714/219.263.specific-Eirik0.asm
This set of commits includes speed improvements for levels 19, 20, and 41, a size improvement for level 28, and a size improvement for the current record for level 23.
=> Update several records

solutions/13-Equalization-Room-9.27/26.15.specific-Eirik0.asm, solutions/31-String-Reverse-11.122/65.51.specific-Eirik0.asm, solutions/32-Inventory-Report-16.393/194.23.exploit-Eirik0.asm, solutions/34-Vowel-Incinerator-13.323/99.95.specific-Eirik0.asm, solutions/41-Sorting-Floor-34.714/219.263.specific-Eirik0.asm
Faster solutions for years 13, 32, and 34, and a tie for the record with less instructions on 31. Also fixed a comment on a previous commit.
=> Some more records

solutions/22-Fibonacci-Visitor-19.156/52.78.specific-gillius.asm
A balanced size/speed solution using pre-computed values supporting any
number of values [-Inf, 21]. It's smaller than the fastest solutions but
not much slower.
=> Balanced Solution to 22-Fibonacci-Visitor

solutions/41-Sorting-Floor-34.714/20.651.selection-sniperrifle2004.asm
This is basically the same algortihm as polarathene's, but written from the ground up. This has resulted in some differences that make the algorithm slightly faster.
=> Faster size 20 selection sort

contributors.yml, solutions/11-Sub-Hallway-10.40/34.34.specific-jdashton.asm, solutions/13-Equalization-Room-9.27/23.15.specific-jdashton.asm
=> Solution in 34 steps for #11

contributors.yml, solutions/21-Zero-Terminated-Sum-10.72/9.88-steambap.asm, solutions/28-Three-Sort-34.78/33.85-steambap.asm, solutions/40-Prime-Factory-28.399/22.423-steambap.asm
Hi, I add my solutions for year 21, 28, and 40 in this commit
=> faster 9 steps program in year 21 and 22 steps for year 40

gulpfile.js, index.html, solutions/02-Busy-Mail-Room-3.25/5.25-jdashton.asm
Surface solutions that are the smallest or fastest within the constraint of achieving the other challenge for the level, e.g. "What's the smallest program that still meets the performance target?
=> Add columns for constrained solutions

solutions/02-Busy-Mail-Room-3.25/3.30-atesgoral.asm
Just fixing a small thing, the part for level 2 is 3.
=> Fix par for level 2

contributors.yml, solutions/19-Countdown-10.82/13.72-tobeannouncd.asm
New solution for 19-Countdown-10.82 that improves upon the previous fastest, non-specific solution
=> Added faster non-specific solution for 19

solutions/12-Tetracontiplier-14.56/14.56.alternative-nanashi-juanto.asm
the order should not include 30n.
=> Edit to comment

solutions/32-Inventory-Report-16.393/13.50.exploit-837951602.asm
=> 13.50 fastest in smallest solutions

contributors.yml, solutions/41-Sorting-Floor-34.714/20.648.selection-mrflip.asm
Moving the increment to the top means one extra tick on the final input but saves a JUMP on the previous 3.
=> Sorting Floor: Minimal size, runs 3 ticks faster

solutions/20-Multiplication-Workshop-15.109/22.105-mrflip.asm
Copying inbox directly to solution before checking zero saves a line
=> One line shorter for Multiplication Workshop

solutions/02-Busy-Mail-Room-3.25/25.20.unrolled-mrflip.asm, solutions/04-Scrambler-Handler-7.21/19.18.unroll-mrflip.asm, solutions/06-Rainy-Summer-6.24/26.20.unroll-mrflip.asm, solutions/23-The-Littlest-Number-13.75/13.70-mrflip.asm, solutions/29-Storage-Floor-5.25/21.20.unroll-mrflip.asm, solutions/35-Duplicate-Removal-17.167/31.138-mrflip.asm, solutions/36-Alphabetizer-39.109/39.59-mrflip.asm, solutions/37-Scavenger-Chain-8.63/44.56.unroll-mrflip.asm
Most of these are cheap loop unrolls, but might as well be posted.
Fastest within-limits versions of Alphabetizer and Littlest Number.
Fastest overweight solutions for Busy Mail Room, Scrambler Handler, Rainy Summer, Storage Floor, Duplicate Removal, and Scavenger Chain.
=> Several fastest-overweights; fastest-within-limits Alphabetizer and Littlest Number

solutions/41-Sorting-Floor-34.714/43.621-insert-dubaaron.asm
This one is middle-of-the-road in both size and speed, a bit above par for size, a bit below par for speed.
=> Add another insert sort solution for level 41

index.html
Adding @viamodulo, for contributing record-breaking new solutions and for reviewing and fixing existing solutions, as a maintainer.
=> Add viamodulo to maintainers

contributors.yml, solutions/04-Scrambler-Handler-7.21/14.19.unroll-ad-pro.asm
Partially unrolled cycle.
Size 14, Speed  19
=> Improved solution for 04-Scrumbler-Handler

solutions/23-The-Littlest-Number-13.75/43.63-icez.asm, solutions/24-Mod-Module-12.57/32.44-icez.asm, solutions/26-Small-Divide-15.76/99.46-icez.asm, solutions/36-Alphabetizer-39.109/63.55-icez.asm
The top score page should be updated, by the way.
=> Faster non-specific solutions for mission 23,24,26,36

.github/workflows/build-and-deploy.yml, .github/workflows/test.yml
@clarfonthey @viamodulo turns out I wasn't running the tests on PRs 🤦
=> Run tests on PRs

gulpfile.js, package.json, yarn.lock
=> Update hrm-level-outbox-generator and remove local patches
